sudo: required
dist: trusty

language: haxe

# Add encrypted API key
env:
  global:
    - secure: lqLKOiu3XIy5zcvw2XO9cj62fSpUDuKo2lOOS5I+jAADUyZmhIMfO2cdyAud3SrOKo5DYtbS4v3doTdhhvbk8LHR5cmIJE7SmRxMGAKVJV2lmcP/7naXc6CfcxvItrM5vx9y1LfJ8pq2B2nDdd7KKjqfD89ycEBXezalJ9Q8BRfcDJQ34oiwm6hLIG9rQ4Wz5YoJsfMbm7/dL4A8kqbCihdINyRR7ZdGNs08LDoqqWtJU9GMF1i70r6WK5NmXIaV+Gv3WLZEV7Ugl+Z8j9gzcIZseODEvkGtsvpeY8xQOE7DP9zSKXxsuxOIhZop/0hdR3dkVrUP9hUwZIlpvSn2qOnSBo+RVTdzwqNJTLC9n+SUk0qVPw4JMt24fjvizO3sHnTEfEIzyoe7sUBd8NOzKFu6pZNF0qnb9skcmfkTGgLhFI4u0lHvXXLrs0nkpb9F5XiDyaadtg8Fds9OaBhxkmF9O/iVWPP4l1aRCO7eYlDYwPMAWfBF/YIlpcgkgE1Zl6Bh0XbJb3GrnGxlK0rwRYTGFhsX7KOphfzr+InuFoFD7+Dwvjv8JpOhBp0j5JBRjzVxeXuqkfTp038TFYiHypcfi3aiKkXyRShorugPyEeq7TMc21lTd7KwgfRwvzrT9cYWKB61NgI8ZoKh/9zOwUBPzuv+JGYugy/5Q7PT6bI=

os:
  - linux

addons:
  apt:
    packages:
      - graphviz

# Blacklist
branches:
  only:
    - master

# Build the docs
script:
  - pushd dox
  - haxelib install dox
  - haxelib install haxeumlgen
  - chmod +x generate_docs.sh
  - ./generate_docs.sh
  - popd

# Deploy the generated documentation using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dox/generated_docs
  github_token: $GITHUB_API_KEY
  on:
    branch: master
