sudo: required
dist: trusty

language: haxe

# Add encrypted API key
env:
  global:
    - secure: fJRN5cuu0mEnIy0ycvzab/Ir6Hy/y0r0gGwtk1Q2iIf4lrxe0nLgTy5C87svx+Wb/YL9jkk4/utNUCJwb6KIudq4ED0i1m9gIpwi53QLKJrKgDCp9A66kSfnuCKMH2PDVlT4R3kIhQJx2R3l+wgNfYP/hqvpsfnlFf0meBeShQ9pj6MXMWxf5hYzZPh+dLKzC5PbpcRdff1NG/1yjpzqypsdZXGFFejPT0Z8KeYK83X6V3NmLDPD7gY93IijwF/ASK5qcg4hggGk2+U00WE7XzoI3tFimptjGhRIqcXv7YeAwFuiASL7BuAVnz/1GvmRXJltCkZVdCD+4ijxk82jQWrCraGamUVIQTmCaT7Q8pgtTJuuGo0g4/oBuJ1pLFmFtKuvZFwxYCTeyzNJbFapN06Yl09oDziJj/DbbZRWmtACXYRrn6ff2R/FXHqbLIlNZtiT2QjZJehg5FRBunFaJbwKoKpmj+421DgzrTKE78RMbtRcnydNIqDJEU4Esd+/54vbk9Ly7pVF9k+9EYGQoCWWONoiAgah+tVPTe/SwOqsKi58wxKPFsJmyvXC9nAOC+aHqVWAOiQXobxG+DmlmTTo0sdOy75J8+VpGlWvUXoII9vwc8Xc09ezRmR2lSzXnPBGna7tOlvXyh0AuBWhUqiGuhi6O4Y/icCv1qL2SPU=

os:
  - linux

addons:
  apt:
    packages:
      - graphviz

# Blacklist
branches:
  only:
    - master

# Build the docs
script:
  - pushd dox
  - haxelib install dox
  - haxelib install haxeumlgen
  - chmod +x generate_docs.sh
  - ./generate_docs.sh
  - popd

# Deploy the generated documentation using Travis builtin GitHub Pages support
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  local_dir: dox/generated_docs
  github_token: $GITHUB_API_KEY
  on:
    branch: master